#!/bin/bash
# kalkulator
function wybór2 {
c=0
echo "podaj liczbę (c)"
read c
zm=`echo $c | grep -E "(^*$|^/$|^+$|^-$)" | wc -l`
if [ $zm -eq 1 ]
then
     echo
else
     echo "zły argument"
     return
fi
}
function wybór {
a=0
b=0
echo "podaj dwie liczby (a,b)"
read a
zm=`echo $a | grep -E "(^*$|^/$|^+$|^-$)" | wc -l`
if [ $zm -eq 1 ]
then
     read b
     zm2=`echo $b | grep -E "(^*$|^/$|^+$|^-$)" | wc -l`
       if [ $zm -eq 1 ]
       then 
            echo
      else
           echo "zły argument"
      fi
else
     echo "zły argument"
     return
fi
}
function początek {
echo "wybierz działanie:
1) dodawanie 3) mnożenie 5) potęgowanie
2) odejmowanie 4) dzielenie 6) silnia 7) koniec" 
}
hflag=
vflag=
aflag=
while getopts hvf:q OPT; do
case $OPT in
h) hflag=1;;
v) vflag=1;;
a) aflag=1;;
q) exit;;
*) echo "Bledny arg!";;
esac
done
if [ ! -z $hflag ]; then
echo "----POMOC----"
echo "Jest to prosty skrypt wykonujący działania."
echo
echo "-------------"
fi
if [ ! -z $vflag ]; then
echo "Version 1.0.0.0"
fi
if [ ! -z $aflag ]; then
echo "autor:Magdalena Płotka"
fi
wynik=0
echo "Prosty kalkulator"
echo "wybierz działanie:"
select dz in "dodawanie" "odejmowanie" "mnożenie" "dzielenie" "potęgowanie" "silnia" "koniec" 
do
case $dz in
   "dodawanie") 
wybór
let wynik=$[$a+$b]
echo "$a + $b = $wynik"
początek ;;
    "odejmowanie" ) 
wybór
let wynik=$[$a - $b]
echo "$a - $b = $wynik"
początek ;;
    "mnożenie") 
wybór
let wynik=$[$a * $b]
echo "$a * $b = $wynik"
początek;;
    "dzielenie") 
wybór
if [$b -eq 0]
then
    echo "błąd, nie radzę dzielić przez 0"
    return
else    
     let wynik=$[$a / $b]
     echo "$a / $b = $wynik"
     początek
fi;;
    "potęgowanie") 
wybór2
let wynik=$[$a*$a]
echo "$a^2 = $wynik"
początek;;
    "silnia")
wybór2
 wynik=1
  N=$1
  while [ $N -ge 1 ]
  do
    wynik=$[$wynik * $N]
    N=$[$N - 1]
  done
echo "$a != $wynik"
początek;;
    "koniec")
echo "miłego dnia :)" 
exit ;;
    *) echo "Nic nie wybrałeś"
  esac
  done
